#########################
# Okyanus Configuration #
#########################

[chat]

# Default chat message format
# First %s is the player name,
# Second %s is the messsage.
# Color supported with the ยง character.
defaultFormat = "<%s> %s"