#########################
# Okyanus Configuration #
#########################

[chat]

# Default chat message format
# First %s is the player name,
# Second %s is the messsage.
# Color supported with the ยง character.
defaultFormat = "<%s> %s"


[optimizations]

maxBookPageSize = 2560
maxBookTotalSizeMultiplier = 0.98

fastExplosions = true

# Probably buggy, be careful!
fastRedstone = true